// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MvvmBasicParam.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MvvmBasicParam_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MvvmBasicParam_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MvvmBasicParam_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MvvmBasicParam_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MvvmBasicParam_2eproto;
namespace mvvm {
class mvvm_ParamBool;
class mvvm_ParamBoolDefaultTypeInternal;
extern mvvm_ParamBoolDefaultTypeInternal _mvvm_ParamBool_default_instance_;
class mvvm_ParamInt32;
class mvvm_ParamInt32DefaultTypeInternal;
extern mvvm_ParamInt32DefaultTypeInternal _mvvm_ParamInt32_default_instance_;
class mvvm_ParamInt64;
class mvvm_ParamInt64DefaultTypeInternal;
extern mvvm_ParamInt64DefaultTypeInternal _mvvm_ParamInt64_default_instance_;
class mvvm_ParamString;
class mvvm_ParamStringDefaultTypeInternal;
extern mvvm_ParamStringDefaultTypeInternal _mvvm_ParamString_default_instance_;
}  // namespace mvvm
PROTOBUF_NAMESPACE_OPEN
template<> ::mvvm::mvvm_ParamBool* Arena::CreateMaybeMessage<::mvvm::mvvm_ParamBool>(Arena*);
template<> ::mvvm::mvvm_ParamInt32* Arena::CreateMaybeMessage<::mvvm::mvvm_ParamInt32>(Arena*);
template<> ::mvvm::mvvm_ParamInt64* Arena::CreateMaybeMessage<::mvvm::mvvm_ParamInt64>(Arena*);
template<> ::mvvm::mvvm_ParamString* Arena::CreateMaybeMessage<::mvvm::mvvm_ParamString>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mvvm {

// ===================================================================

class mvvm_ParamString :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mvvm.mvvm_ParamString) */ {
 public:
  mvvm_ParamString();
  virtual ~mvvm_ParamString();

  mvvm_ParamString(const mvvm_ParamString& from);
  mvvm_ParamString(mvvm_ParamString&& from) noexcept
    : mvvm_ParamString() {
    *this = ::std::move(from);
  }

  inline mvvm_ParamString& operator=(const mvvm_ParamString& from) {
    CopyFrom(from);
    return *this;
  }
  inline mvvm_ParamString& operator=(mvvm_ParamString&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const mvvm_ParamString& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mvvm_ParamString* internal_default_instance() {
    return reinterpret_cast<const mvvm_ParamString*>(
               &_mvvm_ParamString_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(mvvm_ParamString& a, mvvm_ParamString& b) {
    a.Swap(&b);
  }
  inline void Swap(mvvm_ParamString* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline mvvm_ParamString* New() const final {
    return CreateMaybeMessage<mvvm_ParamString>(nullptr);
  }

  mvvm_ParamString* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<mvvm_ParamString>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const mvvm_ParamString& from);
  void MergeFrom(const mvvm_ParamString& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mvvm_ParamString* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mvvm.mvvm_ParamString";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MvvmBasicParam_2eproto);
    return ::descriptor_table_MvvmBasicParam_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // string value = 1;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:mvvm.mvvm_ParamString)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MvvmBasicParam_2eproto;
};
// -------------------------------------------------------------------

class mvvm_ParamInt32 :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mvvm.mvvm_ParamInt32) */ {
 public:
  mvvm_ParamInt32();
  virtual ~mvvm_ParamInt32();

  mvvm_ParamInt32(const mvvm_ParamInt32& from);
  mvvm_ParamInt32(mvvm_ParamInt32&& from) noexcept
    : mvvm_ParamInt32() {
    *this = ::std::move(from);
  }

  inline mvvm_ParamInt32& operator=(const mvvm_ParamInt32& from) {
    CopyFrom(from);
    return *this;
  }
  inline mvvm_ParamInt32& operator=(mvvm_ParamInt32&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const mvvm_ParamInt32& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mvvm_ParamInt32* internal_default_instance() {
    return reinterpret_cast<const mvvm_ParamInt32*>(
               &_mvvm_ParamInt32_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(mvvm_ParamInt32& a, mvvm_ParamInt32& b) {
    a.Swap(&b);
  }
  inline void Swap(mvvm_ParamInt32* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline mvvm_ParamInt32* New() const final {
    return CreateMaybeMessage<mvvm_ParamInt32>(nullptr);
  }

  mvvm_ParamInt32* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<mvvm_ParamInt32>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const mvvm_ParamInt32& from);
  void MergeFrom(const mvvm_ParamInt32& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mvvm_ParamInt32* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mvvm.mvvm_ParamInt32";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MvvmBasicParam_2eproto);
    return ::descriptor_table_MvvmBasicParam_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // int32 value = 1;
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int32 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_value() const;
  void _internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:mvvm.mvvm_ParamInt32)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MvvmBasicParam_2eproto;
};
// -------------------------------------------------------------------

class mvvm_ParamBool :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mvvm.mvvm_ParamBool) */ {
 public:
  mvvm_ParamBool();
  virtual ~mvvm_ParamBool();

  mvvm_ParamBool(const mvvm_ParamBool& from);
  mvvm_ParamBool(mvvm_ParamBool&& from) noexcept
    : mvvm_ParamBool() {
    *this = ::std::move(from);
  }

  inline mvvm_ParamBool& operator=(const mvvm_ParamBool& from) {
    CopyFrom(from);
    return *this;
  }
  inline mvvm_ParamBool& operator=(mvvm_ParamBool&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const mvvm_ParamBool& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mvvm_ParamBool* internal_default_instance() {
    return reinterpret_cast<const mvvm_ParamBool*>(
               &_mvvm_ParamBool_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(mvvm_ParamBool& a, mvvm_ParamBool& b) {
    a.Swap(&b);
  }
  inline void Swap(mvvm_ParamBool* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline mvvm_ParamBool* New() const final {
    return CreateMaybeMessage<mvvm_ParamBool>(nullptr);
  }

  mvvm_ParamBool* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<mvvm_ParamBool>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const mvvm_ParamBool& from);
  void MergeFrom(const mvvm_ParamBool& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mvvm_ParamBool* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mvvm.mvvm_ParamBool";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MvvmBasicParam_2eproto);
    return ::descriptor_table_MvvmBasicParam_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // bool value = 1;
  void clear_value();
  bool value() const;
  void set_value(bool value);
  private:
  bool _internal_value() const;
  void _internal_set_value(bool value);
  public:

  // @@protoc_insertion_point(class_scope:mvvm.mvvm_ParamBool)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  bool value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MvvmBasicParam_2eproto;
};
// -------------------------------------------------------------------

class mvvm_ParamInt64 :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mvvm.mvvm_ParamInt64) */ {
 public:
  mvvm_ParamInt64();
  virtual ~mvvm_ParamInt64();

  mvvm_ParamInt64(const mvvm_ParamInt64& from);
  mvvm_ParamInt64(mvvm_ParamInt64&& from) noexcept
    : mvvm_ParamInt64() {
    *this = ::std::move(from);
  }

  inline mvvm_ParamInt64& operator=(const mvvm_ParamInt64& from) {
    CopyFrom(from);
    return *this;
  }
  inline mvvm_ParamInt64& operator=(mvvm_ParamInt64&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const mvvm_ParamInt64& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const mvvm_ParamInt64* internal_default_instance() {
    return reinterpret_cast<const mvvm_ParamInt64*>(
               &_mvvm_ParamInt64_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(mvvm_ParamInt64& a, mvvm_ParamInt64& b) {
    a.Swap(&b);
  }
  inline void Swap(mvvm_ParamInt64* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline mvvm_ParamInt64* New() const final {
    return CreateMaybeMessage<mvvm_ParamInt64>(nullptr);
  }

  mvvm_ParamInt64* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<mvvm_ParamInt64>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const mvvm_ParamInt64& from);
  void MergeFrom(const mvvm_ParamInt64& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(mvvm_ParamInt64* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mvvm.mvvm_ParamInt64";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MvvmBasicParam_2eproto);
    return ::descriptor_table_MvvmBasicParam_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // int64 value = 1;
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int64 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_value() const;
  void _internal_set_value(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:mvvm.mvvm_ParamInt64)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MvvmBasicParam_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// mvvm_ParamString

// string value = 1;
inline void mvvm_ParamString::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& mvvm_ParamString::value() const {
  // @@protoc_insertion_point(field_get:mvvm.mvvm_ParamString.value)
  return _internal_value();
}
inline void mvvm_ParamString::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:mvvm.mvvm_ParamString.value)
}
inline std::string* mvvm_ParamString::mutable_value() {
  // @@protoc_insertion_point(field_mutable:mvvm.mvvm_ParamString.value)
  return _internal_mutable_value();
}
inline const std::string& mvvm_ParamString::_internal_value() const {
  return value_.GetNoArena();
}
inline void mvvm_ParamString::_internal_set_value(const std::string& value) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void mvvm_ParamString::set_value(std::string&& value) {
  
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mvvm.mvvm_ParamString.value)
}
inline void mvvm_ParamString::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mvvm.mvvm_ParamString.value)
}
inline void mvvm_ParamString::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mvvm.mvvm_ParamString.value)
}
inline std::string* mvvm_ParamString::_internal_mutable_value() {
  
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* mvvm_ParamString::release_value() {
  // @@protoc_insertion_point(field_release:mvvm.mvvm_ParamString.value)
  
  return value_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void mvvm_ParamString::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:mvvm.mvvm_ParamString.value)
}

// -------------------------------------------------------------------

// mvvm_ParamInt32

// int32 value = 1;
inline void mvvm_ParamInt32::clear_value() {
  value_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 mvvm_ParamInt32::_internal_value() const {
  return value_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 mvvm_ParamInt32::value() const {
  // @@protoc_insertion_point(field_get:mvvm.mvvm_ParamInt32.value)
  return _internal_value();
}
inline void mvvm_ParamInt32::_internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  value_ = value;
}
inline void mvvm_ParamInt32::set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:mvvm.mvvm_ParamInt32.value)
}

// -------------------------------------------------------------------

// mvvm_ParamBool

// bool value = 1;
inline void mvvm_ParamBool::clear_value() {
  value_ = false;
}
inline bool mvvm_ParamBool::_internal_value() const {
  return value_;
}
inline bool mvvm_ParamBool::value() const {
  // @@protoc_insertion_point(field_get:mvvm.mvvm_ParamBool.value)
  return _internal_value();
}
inline void mvvm_ParamBool::_internal_set_value(bool value) {
  
  value_ = value;
}
inline void mvvm_ParamBool::set_value(bool value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:mvvm.mvvm_ParamBool.value)
}

// -------------------------------------------------------------------

// mvvm_ParamInt64

// int64 value = 1;
inline void mvvm_ParamInt64::clear_value() {
  value_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 mvvm_ParamInt64::_internal_value() const {
  return value_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 mvvm_ParamInt64::value() const {
  // @@protoc_insertion_point(field_get:mvvm.mvvm_ParamInt64.value)
  return _internal_value();
}
inline void mvvm_ParamInt64::_internal_set_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  value_ = value;
}
inline void mvvm_ParamInt64::set_value(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:mvvm.mvvm_ParamInt64.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mvvm

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MvvmBasicParam_2eproto
