// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MvvmBasicParam.proto

#include "MvvmBasicParam.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace mvvm {
class mvvm_ParamStringDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<mvvm_ParamString> _instance;
} _mvvm_ParamString_default_instance_;
class mvvm_ParamInt32DefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<mvvm_ParamInt32> _instance;
} _mvvm_ParamInt32_default_instance_;
class mvvm_ParamBoolDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<mvvm_ParamBool> _instance;
} _mvvm_ParamBool_default_instance_;
class mvvm_ParamInt64DefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<mvvm_ParamInt64> _instance;
} _mvvm_ParamInt64_default_instance_;
}  // namespace mvvm
static void InitDefaultsscc_info_mvvm_ParamBool_MvvmBasicParam_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mvvm::_mvvm_ParamBool_default_instance_;
    new (ptr) ::mvvm::mvvm_ParamBool();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mvvm::mvvm_ParamBool::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_mvvm_ParamBool_MvvmBasicParam_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_mvvm_ParamBool_MvvmBasicParam_2eproto}, {}};

static void InitDefaultsscc_info_mvvm_ParamInt32_MvvmBasicParam_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mvvm::_mvvm_ParamInt32_default_instance_;
    new (ptr) ::mvvm::mvvm_ParamInt32();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mvvm::mvvm_ParamInt32::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_mvvm_ParamInt32_MvvmBasicParam_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_mvvm_ParamInt32_MvvmBasicParam_2eproto}, {}};

static void InitDefaultsscc_info_mvvm_ParamInt64_MvvmBasicParam_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mvvm::_mvvm_ParamInt64_default_instance_;
    new (ptr) ::mvvm::mvvm_ParamInt64();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mvvm::mvvm_ParamInt64::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_mvvm_ParamInt64_MvvmBasicParam_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_mvvm_ParamInt64_MvvmBasicParam_2eproto}, {}};

static void InitDefaultsscc_info_mvvm_ParamString_MvvmBasicParam_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mvvm::_mvvm_ParamString_default_instance_;
    new (ptr) ::mvvm::mvvm_ParamString();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mvvm::mvvm_ParamString::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_mvvm_ParamString_MvvmBasicParam_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_mvvm_ParamString_MvvmBasicParam_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MvvmBasicParam_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MvvmBasicParam_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MvvmBasicParam_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MvvmBasicParam_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamString, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamString, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamInt32, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamInt32, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamBool, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamBool, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamInt64, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::mvvm::mvvm_ParamInt64, value_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mvvm::mvvm_ParamString)},
  { 6, -1, sizeof(::mvvm::mvvm_ParamInt32)},
  { 12, -1, sizeof(::mvvm::mvvm_ParamBool)},
  { 18, -1, sizeof(::mvvm::mvvm_ParamInt64)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mvvm::_mvvm_ParamString_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mvvm::_mvvm_ParamInt32_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mvvm::_mvvm_ParamBool_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::mvvm::_mvvm_ParamInt64_default_instance_),
};

const char descriptor_table_protodef_MvvmBasicParam_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024MvvmBasicParam.proto\022\004mvvm\"!\n\020mvvm_Par"
  "amString\022\r\n\005value\030\001 \001(\t\" \n\017mvvm_ParamInt"
  "32\022\r\n\005value\030\001 \001(\005\"\037\n\016mvvm_ParamBool\022\r\n\005v"
  "alue\030\001 \001(\010\" \n\017mvvm_ParamInt64\022\r\n\005value\030\001"
  " \001(\003b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MvvmBasicParam_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MvvmBasicParam_2eproto_sccs[4] = {
  &scc_info_mvvm_ParamBool_MvvmBasicParam_2eproto.base,
  &scc_info_mvvm_ParamInt32_MvvmBasicParam_2eproto.base,
  &scc_info_mvvm_ParamInt64_MvvmBasicParam_2eproto.base,
  &scc_info_mvvm_ParamString_MvvmBasicParam_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MvvmBasicParam_2eproto_once;
static bool descriptor_table_MvvmBasicParam_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MvvmBasicParam_2eproto = {
  &descriptor_table_MvvmBasicParam_2eproto_initialized, descriptor_table_protodef_MvvmBasicParam_2eproto, "MvvmBasicParam.proto", 172,
  &descriptor_table_MvvmBasicParam_2eproto_once, descriptor_table_MvvmBasicParam_2eproto_sccs, descriptor_table_MvvmBasicParam_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_MvvmBasicParam_2eproto::offsets,
  file_level_metadata_MvvmBasicParam_2eproto, 4, file_level_enum_descriptors_MvvmBasicParam_2eproto, file_level_service_descriptors_MvvmBasicParam_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MvvmBasicParam_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MvvmBasicParam_2eproto), true);
namespace mvvm {

// ===================================================================

void mvvm_ParamString::InitAsDefaultInstance() {
}
class mvvm_ParamString::_Internal {
 public:
};

mvvm_ParamString::mvvm_ParamString()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mvvm.mvvm_ParamString)
}
mvvm_ParamString::mvvm_ParamString(const mvvm_ParamString& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_value().empty()) {
    value_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:mvvm.mvvm_ParamString)
}

void mvvm_ParamString::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_mvvm_ParamString_MvvmBasicParam_2eproto.base);
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

mvvm_ParamString::~mvvm_ParamString() {
  // @@protoc_insertion_point(destructor:mvvm.mvvm_ParamString)
  SharedDtor();
}

void mvvm_ParamString::SharedDtor() {
  value_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void mvvm_ParamString::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const mvvm_ParamString& mvvm_ParamString::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_mvvm_ParamString_MvvmBasicParam_2eproto.base);
  return *internal_default_instance();
}


void mvvm_ParamString::Clear() {
// @@protoc_insertion_point(message_clear_start:mvvm.mvvm_ParamString)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

const char* mvvm_ParamString::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "mvvm.mvvm_ParamString.value"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* mvvm_ParamString::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mvvm.mvvm_ParamString)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string value = 1;
  if (this->value().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mvvm.mvvm_ParamString.value");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mvvm.mvvm_ParamString)
  return target;
}

size_t mvvm_ParamString::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mvvm.mvvm_ParamString)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 1;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void mvvm_ParamString::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mvvm.mvvm_ParamString)
  GOOGLE_DCHECK_NE(&from, this);
  const mvvm_ParamString* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<mvvm_ParamString>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mvvm.mvvm_ParamString)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mvvm.mvvm_ParamString)
    MergeFrom(*source);
  }
}

void mvvm_ParamString::MergeFrom(const mvvm_ParamString& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mvvm.mvvm_ParamString)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void mvvm_ParamString::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mvvm.mvvm_ParamString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mvvm_ParamString::CopyFrom(const mvvm_ParamString& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mvvm.mvvm_ParamString)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mvvm_ParamString::IsInitialized() const {
  return true;
}

void mvvm_ParamString::InternalSwap(mvvm_ParamString* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  value_.Swap(&other->value_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::PROTOBUF_NAMESPACE_ID::Metadata mvvm_ParamString::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void mvvm_ParamInt32::InitAsDefaultInstance() {
}
class mvvm_ParamInt32::_Internal {
 public:
};

mvvm_ParamInt32::mvvm_ParamInt32()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mvvm.mvvm_ParamInt32)
}
mvvm_ParamInt32::mvvm_ParamInt32(const mvvm_ParamInt32& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:mvvm.mvvm_ParamInt32)
}

void mvvm_ParamInt32::SharedCtor() {
  value_ = 0;
}

mvvm_ParamInt32::~mvvm_ParamInt32() {
  // @@protoc_insertion_point(destructor:mvvm.mvvm_ParamInt32)
  SharedDtor();
}

void mvvm_ParamInt32::SharedDtor() {
}

void mvvm_ParamInt32::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const mvvm_ParamInt32& mvvm_ParamInt32::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_mvvm_ParamInt32_MvvmBasicParam_2eproto.base);
  return *internal_default_instance();
}


void mvvm_ParamInt32::Clear() {
// @@protoc_insertion_point(message_clear_start:mvvm.mvvm_ParamInt32)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = 0;
  _internal_metadata_.Clear();
}

const char* mvvm_ParamInt32::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* mvvm_ParamInt32::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mvvm.mvvm_ParamInt32)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mvvm.mvvm_ParamInt32)
  return target;
}

size_t mvvm_ParamInt32::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mvvm.mvvm_ParamInt32)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void mvvm_ParamInt32::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mvvm.mvvm_ParamInt32)
  GOOGLE_DCHECK_NE(&from, this);
  const mvvm_ParamInt32* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<mvvm_ParamInt32>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mvvm.mvvm_ParamInt32)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mvvm.mvvm_ParamInt32)
    MergeFrom(*source);
  }
}

void mvvm_ParamInt32::MergeFrom(const mvvm_ParamInt32& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mvvm.mvvm_ParamInt32)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    _internal_set_value(from._internal_value());
  }
}

void mvvm_ParamInt32::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mvvm.mvvm_ParamInt32)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mvvm_ParamInt32::CopyFrom(const mvvm_ParamInt32& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mvvm.mvvm_ParamInt32)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mvvm_ParamInt32::IsInitialized() const {
  return true;
}

void mvvm_ParamInt32::InternalSwap(mvvm_ParamInt32* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata mvvm_ParamInt32::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void mvvm_ParamBool::InitAsDefaultInstance() {
}
class mvvm_ParamBool::_Internal {
 public:
};

mvvm_ParamBool::mvvm_ParamBool()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mvvm.mvvm_ParamBool)
}
mvvm_ParamBool::mvvm_ParamBool(const mvvm_ParamBool& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:mvvm.mvvm_ParamBool)
}

void mvvm_ParamBool::SharedCtor() {
  value_ = false;
}

mvvm_ParamBool::~mvvm_ParamBool() {
  // @@protoc_insertion_point(destructor:mvvm.mvvm_ParamBool)
  SharedDtor();
}

void mvvm_ParamBool::SharedDtor() {
}

void mvvm_ParamBool::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const mvvm_ParamBool& mvvm_ParamBool::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_mvvm_ParamBool_MvvmBasicParam_2eproto.base);
  return *internal_default_instance();
}


void mvvm_ParamBool::Clear() {
// @@protoc_insertion_point(message_clear_start:mvvm.mvvm_ParamBool)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = false;
  _internal_metadata_.Clear();
}

const char* mvvm_ParamBool::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* mvvm_ParamBool::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mvvm.mvvm_ParamBool)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool value = 1;
  if (this->value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mvvm.mvvm_ParamBool)
  return target;
}

size_t mvvm_ParamBool::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mvvm.mvvm_ParamBool)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool value = 1;
  if (this->value() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void mvvm_ParamBool::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mvvm.mvvm_ParamBool)
  GOOGLE_DCHECK_NE(&from, this);
  const mvvm_ParamBool* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<mvvm_ParamBool>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mvvm.mvvm_ParamBool)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mvvm.mvvm_ParamBool)
    MergeFrom(*source);
  }
}

void mvvm_ParamBool::MergeFrom(const mvvm_ParamBool& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mvvm.mvvm_ParamBool)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    _internal_set_value(from._internal_value());
  }
}

void mvvm_ParamBool::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mvvm.mvvm_ParamBool)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mvvm_ParamBool::CopyFrom(const mvvm_ParamBool& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mvvm.mvvm_ParamBool)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mvvm_ParamBool::IsInitialized() const {
  return true;
}

void mvvm_ParamBool::InternalSwap(mvvm_ParamBool* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata mvvm_ParamBool::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void mvvm_ParamInt64::InitAsDefaultInstance() {
}
class mvvm_ParamInt64::_Internal {
 public:
};

mvvm_ParamInt64::mvvm_ParamInt64()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:mvvm.mvvm_ParamInt64)
}
mvvm_ParamInt64::mvvm_ParamInt64(const mvvm_ParamInt64& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:mvvm.mvvm_ParamInt64)
}

void mvvm_ParamInt64::SharedCtor() {
  value_ = PROTOBUF_LONGLONG(0);
}

mvvm_ParamInt64::~mvvm_ParamInt64() {
  // @@protoc_insertion_point(destructor:mvvm.mvvm_ParamInt64)
  SharedDtor();
}

void mvvm_ParamInt64::SharedDtor() {
}

void mvvm_ParamInt64::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const mvvm_ParamInt64& mvvm_ParamInt64::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_mvvm_ParamInt64_MvvmBasicParam_2eproto.base);
  return *internal_default_instance();
}


void mvvm_ParamInt64::Clear() {
// @@protoc_insertion_point(message_clear_start:mvvm.mvvm_ParamInt64)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear();
}

const char* mvvm_ParamInt64::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int64 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* mvvm_ParamInt64::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mvvm.mvvm_ParamInt64)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mvvm.mvvm_ParamInt64)
  return target;
}

size_t mvvm_ParamInt64::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mvvm.mvvm_ParamInt64)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 value = 1;
  if (this->value() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
        this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void mvvm_ParamInt64::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mvvm.mvvm_ParamInt64)
  GOOGLE_DCHECK_NE(&from, this);
  const mvvm_ParamInt64* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<mvvm_ParamInt64>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mvvm.mvvm_ParamInt64)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mvvm.mvvm_ParamInt64)
    MergeFrom(*source);
  }
}

void mvvm_ParamInt64::MergeFrom(const mvvm_ParamInt64& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mvvm.mvvm_ParamInt64)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value() != 0) {
    _internal_set_value(from._internal_value());
  }
}

void mvvm_ParamInt64::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mvvm.mvvm_ParamInt64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mvvm_ParamInt64::CopyFrom(const mvvm_ParamInt64& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mvvm.mvvm_ParamInt64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mvvm_ParamInt64::IsInitialized() const {
  return true;
}

void mvvm_ParamInt64::InternalSwap(mvvm_ParamInt64* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(value_, other->value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata mvvm_ParamInt64::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace mvvm
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mvvm::mvvm_ParamString* Arena::CreateMaybeMessage< ::mvvm::mvvm_ParamString >(Arena* arena) {
  return Arena::CreateInternal< ::mvvm::mvvm_ParamString >(arena);
}
template<> PROTOBUF_NOINLINE ::mvvm::mvvm_ParamInt32* Arena::CreateMaybeMessage< ::mvvm::mvvm_ParamInt32 >(Arena* arena) {
  return Arena::CreateInternal< ::mvvm::mvvm_ParamInt32 >(arena);
}
template<> PROTOBUF_NOINLINE ::mvvm::mvvm_ParamBool* Arena::CreateMaybeMessage< ::mvvm::mvvm_ParamBool >(Arena* arena) {
  return Arena::CreateInternal< ::mvvm::mvvm_ParamBool >(arena);
}
template<> PROTOBUF_NOINLINE ::mvvm::mvvm_ParamInt64* Arena::CreateMaybeMessage< ::mvvm::mvvm_ParamInt64 >(Arena* arena) {
  return Arena::CreateInternal< ::mvvm::mvvm_ParamInt64 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
